openapi: "3.0.3"
info:
  title: railway-statistics-api
  description: Railway Statistics API
  version: 0.0.1
paths:
  /company:
    get:
      responses:
        200:
          description: _
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Company"
  /company/{companyId}:
    get:
      responses:
        200:
          description: _
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/Company"
  /company/{companyId}/statistics:
    get:
      responses:
        200:
          description: _
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schema/CompanyStatistics"
  /line:
    get:
      responses:
        200:
          description: _
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Line"
                  properties:
                    company:
                      $ref: "#/components/schemas/Company"
components:
  schemas:
    Company:
      type: object
      properties:
        companyId:
          type: integer
        companyName:
          type: string
        companyNameAlias:
          type: string
        companyTypeId:
          type: integer
        corporateColor:
          type: string
        status:
          type: integer
    Line:
      type: object
      properties:
        lineId:
          type: integer
        lineCode:
          type: string
        lineName:
          type: string
        lineNameAlias:
          type: string
        lineNameKana:
          type: string
    CompanyStatistics:
      type: object
      properties:
        companyId:
          type: number
        yaer:
          type: number
        transportPassengersTeikiTsukin:
          type: number
        transportPassengersTeikiTsugaku:
          type: number
        transportPassengersTeikiTotal:
          type: number
        transportPassengersTeikiPercent:
          type: number
        transportPassengersTeikigai:
          type: number
        transportPassengersTeikigaiPercent:
          type: number
        transportPassengersSum:
          type: number
        transportRevenuePassengerTeikiTsukin:
          type: number
        transportRevenuePassengerTeikiTsugaku:
          type: number
        transportRevenuePassengerTeikiTotal:
          type: number
        transportRevenuePassengerTeikigai:
          type: number
        transportRevenuePassengerTotal:
          type: number
